// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jkkbfhffefwozwlphhvt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impra2JmaGZmZWZ3b3p3bHBoaHZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0MDg0NDQsImV4cCI6MjA2Mjk4NDQ0NH0.9QvWJNzPO6eHU04ll4XA0G7CDpw6JJY7aJnuEgEAF8Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);